config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index]
  get 'landing/index'

  root 'landing#index'
  resources :pins
  resources :follows

  get 'me', to: 'feeds#user'
  get 'flat', to: 'feeds#flat'
  get 'aggregated', to: 'feeds#aggregated'

end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
  belongs_to :target, class_name: "User"

  validates :target_id, presence: true
  validates :user, presence: true

  include StreamRails::Activity
  as_activity

  def activity_notify
    [StreamRails.feed_manager.get_notification_feed(self.target_id)]
  end

  def activity_object
    self.target
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :pins
  belongs_to :user

  def user_pin(user = nil)
    self.pins.where(user: user).first
  end

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  belongs_to :influencer

  validates :item, presence: true, :uniqueness => {:scope => :user}
  validates :user, presence: true, :uniqueness => {:scope => :item}

  include StreamRails::Activity
  as_activity

  def activity_object
    self.item
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :follows

  def followed(user = nil)
    self.follows.where(user: user).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :create_enricher
  before_action :authenticate_user!

  def user
    feed = StreamRails.feed_manager.get_user_feed(current_user.id)
    results = feed.get()['results']
    @activities = @enricher.enrich_activities(results)
  end

  def flat
    feed = StreamRails.feed_manager.get_news_feeds(current_user.id)[:flat]
    results = feed.get()['results']
    @activities = @enricher.enrich_activities(results)
  end

  def aggregated
    feed = StreamRails.feed_manager.get_news_feeds(current_user.id)[:aggregated]
    results = feed.get()['results']
    @activities = @enricher.enrich_aggregated_activities(results)
  end

  def create_enricher
    @enricher = StreamRails::Enrich.new
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def create
    follow = Follow.new(follow_params)
    follow.user = current_user
    if follow.save
      StreamRails.feed_manager.follow_user(follow.user_id, follow.target_id)
    end
    session[:return_to] ||= request.referer
    redirect_to session.delete(:return_to)
  end

  def destroy
    follow = Follow.find(params[:id])
    if follow.user_id == current_user.id
      follow.destroy!
      StreamRails.feed_manager.unfollow_user(follow.user_id, follow.target_id)
    end
    session[:return_to] ||= request.referer
    redirect_to session.delete(:return_to)
  end

  private
    def follow_params
      params.require(:follow).permit(:target_id)
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  before_action :sign_in_admin, unless: :user_signed_in?

  def index
    @items = Item.all
  end

  def sign_in_admin
    sign_in (User.where(email: Rails.application.secrets.admin_email).first)
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

  def create
    @pin = Pin.new(pin_params)
    @pin.user = current_user
    @pin.save!
    session[:return_to] ||= request.referer
    redirect_to session.delete(:return_to)
  end

  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy
    session[:return_to] ||= request.referer
    redirect_to session.delete(:return_to)
  end

  private
    def pin_params
      params.require(:pin).permit(:item_id, :influencer_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/activity/_follow.html.erb
<article class="pin">
    <div id="wrapper">
      <div class="col-lg-12">
          <img width='45' height='45' title='' alt='' src='data:image/jpg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDScUHBAWICkiIiAoHx8mKDIsJCYxJx8nLT03MTM0MS46LCs0RDM4NzQ5OjQBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIAC0ALQMBIgACEQEDEQH/xAAbAAACAgMBAAAAAAAAAAAAAAAEBQADAQYHAv/EACoQAAIBAwMCBAcBAAAAAAAAAAECAwAEEQUSMSFBIjJRYRUjYnGB0fAT/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AOhVZDDJO+2JCx9qxBE08yRJyxxTe+kbTY4EtcAHO7Izu45oB00acjLSRqfTmq59KuYhlQJB9H6oj422B8gZ7+Kq5tZmdcRIsZ7nmgW1Kb6jaia1S7RQJNoZwO9KKBloKg3LseQnSvGtMxvSp4VRtrGjTCK8CtxINv57UdqVqt5LiNts6L5WGNw9qBHUqyeCS3fZKuGxnnNW2tjPcjdGF25xuLcUDXRj/rYMknVdxXHt/GkJGCR6VsgVNPsDg52KTk9zWt0E44prFdxXiotxI0M6eWVTjNKqlAZcx7Z7gM5lK4w7dc+EmjNMmhtllMjqgKRnB7+HrScEjg4qUBmo3xu2CqCsS8A9/vQdSpQf/9k='>
          <h2><a href=""><%= activity['object'].name %></a></h2>
          <p>and <%= activity['actor'].name %> are now friends</p>
      </div>
    </div>
</article>

app/views/activity/_pin.html.erb
<article class="pin">
    <figure>
        <div class="pin-image-holder">
            <%= image_tag activity['object'].image, class: "pin-image" %>
        </div>
    </figure>
    <%= render partial: "pins/pin_form", locals: {item: activity['object']} %>
    <footer class="pin-attribution">
        by <a href="{{ URL::route('profile', $item->user->username) }}"><%= activity['actor'].email %></a><% if(activity['time']) %> <%= time_ago_in_words activity['time'] %> ago <% end %>
    </footer>
</article>

app/views/aggregated_activity/_follow.html.erb
<div class="aggregation media">
    <div class="media-body">
        <div class="media-heading">
            <div class="aggregation-header">
                <div class="aggregation-time pull-right">
                    <i class="glyphicon glyphicon-time"></i> <%= time_ago_in_words(activity['updated_at']) %> ago
                </div>
            </div>
        </div>
        <% for activity in activity['activities'] %>
            <%= render_activity activity %>
        <% end %>
    </div>
</div>

app/views/aggregated_activity/_pin.html.erb
<div class="aggregation media">
    <div class="media-body">
        <div class="media-heading">
            <div class="aggregation-header">
                <% if activity['actor_count'] == 1 %>
                    <%= activity['activities'][0]['actor'].name %> pinned <%= pluralize(activity['activity_count'], 'item') %>
                <% elsif activity['actor_count'] == 2 %>
                    <%= activity['activities'][0]['actor'].name %> and <%= activity['activities'][1]['actor'].name %> pinned <%= activity['activity_count'] %> items
                <% else %>
                    <%= activity['activities'][0]['actor'].name %>, <%= activity['activities'][1]['actor'].name %> and <%= activity['actor_count'].name - 2 %> more pinned <%= activity['activity_count'] %> items
                <% end %>
                <div class="aggregation-time pull-right">
                    <i class="glyphicon glyphicon-time"></i> <%= time_ago_in_words(activity['updated_at']) %> ago
                </div>
            </div>
        </div>
        <% for activity in activity['activities'] %>
            <%= render_activity activity %>
        <% end %>
    </div>
</div>

app/views/feeds/aggregated.html.erb
<div id="wrapper">
    <% for activity in @activities %>
        <%= render_activity activity %>
    <% end %>
</div>

app/views/feeds/flat.html.erb
<div class="container">
    <div class="container-pins">
        <% for activity in @activities %>
            <%= render_activity activity %>
        <% end %>
    </div>
</div>

app/views/feeds/user.html.erb
<div class="container">
    <div class="container-pins">
        <% for activity in @activities %>
            <%= render_activity activity %>
        <% end %>
    </div>
</div>

app/views/items/_item.html.erb
<article class="pin">
    <figure>
        <div class="pin-image-holder">
            <% if(item.image) %>
                <%= image_tag item.image, class: "pin-image" %>
            <% else %>
                <%= image_tag item.item.image, class: "pin-image" %>
            <% end %>
        </div>
        <% if(item.message) %>
            <figcaption class="pin-caption">
                <%= item.message %>
            </figcaption>
        <% end %>
    </figure>
    <%= render partial: "pins/pin_form", locals: {item: item} %>
    <footer class="pin-attribution">
        by <a href="{{ URL::route('profile', $item->user->username) }}"><%= item.user %></a><% if(item.created_at) %> <%= time_ago_in_words item.created_at %> ago <% end %>
    </footer>
</article>

app/views/landing/index.html.erb
<div class="container">
    <div class="container-pins">
        <% for item in @items %>
            <%= render partial: "items/item", locals: {item: item} %>
        <% end %>
    </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Menu Bar here</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="<%= 'active' if current_page?(root_path) %>">
                    <a href="<%= root_path %>">Trending</a>
                </li>
                <li class="<%= 'active' if current_page?(flat_path) %>">
                    <a href="<%= flat_path %>"><i class="glyphicon glyphicon-th"></i> Flat Feed</a>
                </li>
                <li class="<%= 'active' if current_page?(aggregated_path) %>">
                    <a href="<%= aggregated_path %>"><i class="glyphicon glyphicon-th-list"></i> Aggregated Feed</a>
                </li>
                <li class="<%= 'active' if current_page?(users_path) %>">
                    <a href="<%= users_path %>"><i class="glyphicon glyphicon-user"></i> People</a>
                </li>
                <% if(user_signed_in?) %>
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="glyphicon"></i>  <%= current_user.name %><b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="<%= me_path %>">My Profile</a></li>
                    </ul>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Streamterest" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Streamterest" %>">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="cleartype" content="on">
    <meta name="msapplication-TileColor" content="#222222">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,500' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <section>
        <article>
          <div class="jumbotron">
              <div class="container">
                  <h1>Stream feed in action</h1>
                  <p>
                      Shabby chic reprehenderit exercitation minim. Heirloom four dollar toast sapiente magna keytar, velit hella venmo flexitarian organic. Microdosing banh mi ullamco, actually excepteur fap kale chips kombucha mixtape enim trust fund locavore neutra migas literally. Velit deserunt selvage fingerstache sint, ullamco locavore typewriter portland mlkshk sunt yr bitters squid reprehenderit. Cred quis photo booth occaecat viral etsy. Narwhal you probably haven't heard of them blue bottle fap salvia. Crucifix anim est try-hard, tumblr knausgaard gastropub ullamco venmo.
                  </p>
                  <p>
                      <a class="btn btn-primary btn-lg" href="#" role="button">
                          <i class="icon-help-circle"></i> Click me
                      </a>
                  </p>
              </div>
          </div>
            <%= render 'layouts/messages' %>
            <%= yield %>
        </article>
    </section>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pins/_pin_form.html.erb
<% if (item.user_pin(current_user)) %>
    <textarea class="form-control" name="message" placeholder="Comment..."></textarea>
    <div class="media">
        <div class="pull-left">
            <%= button_to "Unpin", pin_path(item.user_pin(current_user)), :method => "delete", :class => "btn btn-primary btn-sm btn-danger" %>
        </div>
        <div class="media-body">
            <div class="input-group input-group-sm">
                <span class="input-group-addon text-muted">in</span>
                <input class="form-control" name="board_name" placeholder="Board name" type="text" value="My favourite things">
            </div>
        </div>
    </div>
<% else %>
    <%= form_for :pin, url: pins_path do |f| %>
        <textarea class="form-control" name="message" placeholder="Comment..."></textarea>
        <div class="media">
            <div class="pull-left">
                <input class="btn btn-primary btn-sm" type="submit" value="Pin">
            </div>
            <div class="media-body">
                <div class="input-group input-group-sm">
                    <span class="input-group-addon text-muted">in</span>
                    <input class="form-control" name="board_name" placeholder="Board name" type="text" value="My favourite things">
                </div>
            </div>
        </div>
        <%= f.hidden_field :influencer_id %>
        <%= f.hidden_field :item_id, :value => item.id %>
    <% end %>
<% end %>

app/views/users/_profile.html.erb
<img width='45' height='45' title='' alt='' src='data:image/jpg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDScUHBAWICkiIiAoHx8mKDIsJCYxJx8nLT03MTM0MS46LCs0RDM4NzQ5OjQBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIAC0ALQMBIgACEQEDEQH/xAAbAAACAgMBAAAAAAAAAAAAAAAEBQADAQYHAv/EACoQAAIBAwMCBAcBAAAAAAAAAAECAwAEEQUSMSFBIjJRYRUjYnGB0fAT/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AOhVZDDJO+2JCx9qxBE08yRJyxxTe+kbTY4EtcAHO7Izu45oB00acjLSRqfTmq59KuYhlQJB9H6oj422B8gZ7+Kq5tZmdcRIsZ7nmgW1Kb6jaia1S7RQJNoZwO9KKBloKg3LseQnSvGtMxvSp4VRtrGjTCK8CtxINv57UdqVqt5LiNts6L5WGNw9qBHUqyeCS3fZKuGxnnNW2tjPcjdGF25xuLcUDXRj/rYMknVdxXHt/GkJGCR6VsgVNPsDg52KTk9zWt0E44prFdxXiotxI0M6eWVTjNKqlAZcx7Z7gM5lK4w7dc+EmjNMmhtllMjqgKRnB7+HrScEjg4qUBmo3xu2CqCsS8A9/vQdSpQf/9k='>
<h2><a href="{{ URL::route('profile', $profile->username) }}"><%= user.email.split('@')[0] %></a></h2>
<p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>

<% if user.followed(current_user) %>
    <%= button_to "Unfollow", follow_path(user.followed(current_user)), :method => "delete", :class => "btn btn-primary btn-sm btn-danger" %>
<% else %>
  <%= form_for :follow, url: follows_path do |f| %>
    <%= f.hidden_field :target_id, :value => user.id %>
    <input class="btn btn-primary btn-sm btn-default" type="submit" value="Follow">
  <% end %>
<% end %>


<% if @activities %>
  <% @activities.each do |activity| %>
      <%= render_activity activity %>
  <% end %>
<% end %>

app/views/users/_profile_full.html.erb
<div id="wrapper">
    <div class="col-lg-4">
      <%= yield %>
    </div>
    <div class="col-lg-8">
        <div class="container-pins profile">
          <%= yield :side %>
        </div>
    </div>
</div>

app/views/users/_profile_small.html.erb
<div id="wrapper">
    <div class="col-lg-4">
      <%= yield %>
    </div>
</div>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <%= render partial: "profile", layout: "profile_small", locals: {user: user} %>
  <% end %>
</ul>